/**
 * Core type definitions for @diabolicallabs/agent-sdk.
 * Matches the spec in briefs/brief-platform.md §4.2.
 */

import type { LlmClient } from '@diabolicallabs/llm-client';

// Identifies a call's origin for cost attribution
export interface AgentIdentity {
  agentId: string; // UUID — from the Spend Dashboard agent registry
  taskLabel?: string; // Optional free-text, max 200 chars
  projectId?: string; // Optional override; falls back to agent's registered project
}

// Config for the SDK middleware
export interface AgentSdkConfig {
  identity: AgentIdentity;
  ingestionUrl: string; // e.g. 'https://spend.diabolicallabs.studio/api/ingest'
  ingestionKey: string; // agent-scoped bearer token — never log this
  maxIngestionRetries?: number; // default: 3
  ingestionTimeoutMs?: number; // default: 5000 — never block the main call
  disabled?: boolean; // set true to skip all instrumentation (test/dev mode)
}

// An instrumented LlmClient — same interface as LlmClient, adds cost capture
export interface InstrumentedLlmClient extends LlmClient {
  readonly sdkConfig: Readonly<AgentSdkConfig>;
}

// The ingestion payload shape — this is the contract the Spend Dashboard ingests.
// Matches the /api/ingest endpoint body defined in the Agent Spend Dashboard brief.
export interface CallRecord {
  agent_id: string;
  model: string;
  prompt_tokens: number;
  completion_tokens: number;
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  latency_ms: number;
  task_label?: string;
  project_id?: string;
  timestamp: string; // ISO 8601
  call_id: string; // UUID idempotency key, generated by SDK
}
