/**
 * Core type definitions for @diabolicallabs/agent-sdk.
 * Matches the spec in briefs/brief-platform.md §4.2.
 *
 * v1.1.0 additions:
 *   CallRecord.cost — optional USD cost breakdown, propagated from LlmResponse.cost
 *                     when @diabolicallabs/llm-client is configured with pricing.
 *                     Only present when the calling LlmClient has pricing configured
 *                     and @diabolicallabs/llm-pricing is installed.
 *
 * v1.2.0 additions:
 *   CallRecord.requestedModel — optional string; present when llm-client provider failover
 *                               fired. model = actually-serving model; requestedModel = primary.
 *
 * v3.0.1 notes:
 *   LlmCost is defined inline here (Option 2). The peer-dep on @diabolicallabs/llm-pricing was
 *   removed in v3.0.1 — it was type-only and compiled away at build time. The type is inlined to
 *   ensure consumers in environments that don't transitively resolve types continue to compile
 *   cleanly without installing llm-pricing. Shape matches llm-pricing's LlmCost exactly — if the
 *   shapes ever diverge, the workspace typecheck will catch the boundary mismatch.
 */

import type { LlmClient, LlmToolCall } from '@diabolicallabs/llm-client';

/**
 * USD cost breakdown for a single LLM call.
 * Inlined from @diabolicallabs/llm-pricing — no runtime dependency required.
 * Shape is kept in sync with llm-pricing's LlmCost via workspace typecheck.
 */
export interface LlmCost {
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
  total: number;
  currency: string;
  isPartial?: boolean;
}

// Identifies a call's origin for cost attribution
export interface AgentIdentity {
  agentId: string; // UUID — from the Spend Dashboard agent registry
  taskLabel?: string; // Optional free-text, max 200 chars
  projectId?: string; // Optional override; falls back to agent's registered project
}

// Config for the SDK middleware
export interface AgentSdkConfig {
  identity: AgentIdentity;
  ingestionUrl: string; // e.g. 'https://spend.diabolicallabs.studio/api/ingest'
  ingestionKey: string; // agent-scoped bearer token — never log this
  maxIngestionRetries?: number; // default: 3
  ingestionTimeoutMs?: number; // default: 5000 — never block the main call
  disabled?: boolean; // set true to skip all instrumentation (test/dev mode)
}

// An instrumented LlmClient — same interface as LlmClient, adds cost capture
export interface InstrumentedLlmClient extends LlmClient {
  readonly sdkConfig: Readonly<AgentSdkConfig>;
}

// The ingestion payload shape — this is the contract the Spend Dashboard ingests.
// Matches the /api/ingest endpoint body defined in the Agent Spend Dashboard brief.
export interface CallRecord {
  agent_id: string;
  model: string;
  /**
   * The originally-requested primary model (v1.2.0+).
   * Populated only when provider failover occurred — i.e. when LlmResponse.requestedModel
   * is set. When present, model holds the actually-serving fallback model and requestedModel
   * holds what was originally configured as the primary.
   * Undefined when no failover happened.
   */
  requestedModel?: string;
  prompt_tokens: number;
  completion_tokens: number;
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  latency_ms: number;
  task_label?: string;
  project_id?: string;
  timestamp: string; // ISO 8601
  call_id: string; // UUID idempotency key, generated by SDK
  // Present when the call was made via withTools() — enables per-tool cost attribution.
  tool_calls?: LlmToolCall[];
  /**
   * USD cost breakdown for this call (v1.1.0+).
   * Propagated from LlmResponse.cost when the wrapping LlmClient has pricing configured.
   * Undefined when pricing is not configured on the LlmClient, or when stream() is used
   * (streaming does not return a single accumulated response object with a cost field).
   */
  cost?: LlmCost;
}
