/**
 * Default pricing table for @diabolicallabs/llm-pricing.
 *
 * AUTO-GENERATED — do not edit directly.
 * Source of truth: pricing/table.json
 * Regenerate: node pricing/sync-bundled.mjs
 *
 * Data sourced from Tom's Wave 2a pricing snapshot (2026-05-13).
 * Confidence: High for Anthropic, Gemini, DeepSeek, Perplexity (first-party docs).
 *             Medium for OpenAI (primary pricing page 403'd; cross-referenced from
 *             pricepertoken.com + devtk.ai + OpenRouter — all consistent).
 *
 * All prices are USD per 1 million tokens.
 *
 * Maintenance: edit pricing/table.json + run node pricing/sync-bundled.mjs.
 * See pricing/README.md for the full refresh workflow.
 */

import type { PricingTable } from './types.js';

export const DEFAULT_PRICING_TABLE: PricingTable = {
  versionedAt: '2026-08-18',

  anthropic: {
    'claude-fable-5': {
      cacheReadPer1M: 1,
      cacheWrite1hPer1M: 20,
      cacheWritePer1M: 12.5,
      inputPer1M: 10,
      outputPer1M: 50,
      sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
      verifiedAt: '2026-07-25',
    },
    'claude-haiku-3': {
      cacheReadPer1M: 0.03,
      cacheWrite1hPer1M: 0.5,
      cacheWritePer1M: 0.3125,
      inputPer1M: 0.25,
      notes:
        'Retired 2026-04-20 — no longer served on the first-party API. Price retained for historical cost calculations only.',
      outputPer1M: 1.25,
      sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
      verifiedAt: '2026-08-18',
    },
    'claude-haiku-3-5': {
      cacheReadPer1M: 0.08,
      cacheWrite1hPer1M: 1.6,
      cacheWritePer1M: 1,
      inputPer1M: 0.8,
      notes:
        "Retired from Anthropic's first-party API 2026-02-19; still available via Bedrock/Google Cloud at this rate.",
      outputPer1M: 4,
      sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
      verifiedAt: '2026-08-18',
    },
    'claude-haiku-4-5': {
      cacheReadPer1M: 0.1,
      cacheWrite1hPer1M: 2,
      cacheWritePer1M: 1.25,
      inputPer1M: 1,
      outputPer1M: 5,
      sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
      verifiedAt: '2026-07-25',
    },
    'claude-haiku-4-5-20251001': {
      cacheReadPer1M: 0.1,
      cacheWrite1hPer1M: 2,
      cacheWritePer1M: 1.25,
      inputPer1M: 1,
      outputPer1M: 5,
      sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
      verifiedAt: '2026-07-25',
    },
    'claude-mythos-5': {
      cacheReadPer1M: 1,
      cacheWrite1hPer1M: 20,
      cacheWritePer1M: 12.5,
      inputPer1M: 10,
      notes: 'Glasswing-only niche model — same pricing tier as claude-fable-5.',
      outputPer1M: 50,
      sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
      verifiedAt: '2026-07-25',
    },
    'claude-opus-4-5': {
      cacheReadPer1M: 0.5,
      cacheWrite1hPer1M: 10,
      cacheWritePer1M: 6.25,
      inputPer1M: 5,
      outputPer1M: 25,
      sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
      verifiedAt: '2026-07-25',
    },
    'claude-opus-4-6': {
      cacheReadPer1M: 0.5,
      cacheWrite1hPer1M: 10,
      cacheWritePer1M: 6.25,
      inputPer1M: 5,
      outputPer1M: 25,
      sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
      verifiedAt: '2026-07-25',
    },
    'claude-opus-4-7': {
      cacheReadPer1M: 0.5,
      cacheWrite1hPer1M: 10,
      cacheWritePer1M: 6.25,
      inputPer1M: 5,
      outputPer1M: 25,
      sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
      verifiedAt: '2026-07-25',
    },
    'claude-opus-4-8': {
      cacheReadPer1M: 0.5,
      cacheWrite1hPer1M: 10,
      cacheWritePer1M: 6.25,
      inputPer1M: 5,
      outputPer1M: 25,
      sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
      verifiedAt: '2026-07-25',
    },
    'claude-opus-5': {
      cacheReadPer1M: 0.5,
      cacheWrite1hPer1M: 10,
      cacheWritePer1M: 6.25,
      inputPer1M: 5,
      outputPer1M: 25,
      sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
      verifiedAt: '2026-07-25',
    },
    'claude-sonnet-4-5': {
      cacheReadPer1M: 0.3,
      cacheWrite1hPer1M: 6,
      cacheWritePer1M: 3.75,
      inputPer1M: 3,
      outputPer1M: 15,
      sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
      verifiedAt: '2026-07-25',
    },
    'claude-sonnet-4-5-20250929': {
      cacheReadPer1M: 0.3,
      cacheWrite1hPer1M: 6,
      cacheWritePer1M: 3.75,
      inputPer1M: 3,
      outputPer1M: 15,
      sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
      verifiedAt: '2026-07-25',
    },
    'claude-sonnet-4-6': {
      cacheReadPer1M: 0.3,
      cacheWrite1hPer1M: 6,
      cacheWritePer1M: 3.75,
      inputPer1M: 3,
      outputPer1M: 15,
      sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
      verifiedAt: '2026-07-25',
    },
    'claude-sonnet-5': {
      cacheReadPer1M: 0.2,
      cacheWrite1hPer1M: 4,
      cacheWritePer1M: 2.5,
      inputPer1M: 2,
      notes:
        "Permanent rate — Anthropic cancelled the planned 2026-08-31 increase to $3/$15 and made the $2/$10 rate standard. Do not 'correct' this back to $3/$15.",
      outputPer1M: 10,
      sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
      verifiedAt: '2026-08-18',
    },
  },

  openai: {
    'gpt-4.1': {
      cacheReadPer1M: 0.5,
      inputPer1M: 2,
      notes:
        'Scheduled shutdown 2026-10-23 (OpenAI deprecations page) — migrate consumers to gpt-5.6-sol/terra/luna before then.',
      outputPer1M: 8,
      sourceUrl: 'https://pricepertoken.com/pricing-page/provider/openai',
      verifiedAt: '2026-08-18',
    },
    'gpt-4o': {
      cacheReadPer1M: 1.25,
      inputPer1M: 2.5,
      outputPer1M: 10,
      sourceUrl: 'https://pricepertoken.com/pricing-page/model/openai-gpt-4o',
      verifiedAt: '2026-05-18',
    },
    'gpt-4o-mini': {
      cacheReadPer1M: 0.075,
      inputPer1M: 0.15,
      outputPer1M: 0.6,
      sourceUrl: 'https://pricepertoken.com/pricing-page/model/openai-gpt-4o-mini',
      verifiedAt: '2026-05-18',
    },
    'gpt-5.1': {
      cacheReadPer1M: 0.125,
      inputPer1M: 1.25,
      outputPer1M: 10,
      sourceUrl: 'https://portkey.ai/models/openai',
      verifiedAt: '2026-05-18',
    },
    'gpt-5.1-codex-mini': {
      cacheReadPer1M: 0.025,
      inputPer1M: 0.25,
      outputPer1M: 2,
      sourceUrl: 'https://portkey.ai/models/openai',
      verifiedAt: '2026-05-18',
    },
    'gpt-5.2': {
      cacheReadPer1M: 0.175,
      inputPer1M: 1.75,
      outputPer1M: 14,
      sourceUrl: 'https://portkey.ai/models/openai',
      verifiedAt: '2026-05-18',
    },
    'gpt-5.2-codex': {
      cacheReadPer1M: 0.175,
      inputPer1M: 1.75,
      outputPer1M: 14,
      sourceUrl: 'https://portkey.ai/models/openai',
      verifiedAt: '2026-05-18',
    },
    'gpt-5.2-pro': {
      cacheReadPer1M: 2.1,
      inputPer1M: 21,
      outputPer1M: 168,
      sourceUrl: 'https://portkey.ai/models/openai',
      verifiedAt: '2026-05-18',
    },
    'gpt-5.3-chat-latest': {
      cacheReadPer1M: 0.175,
      inputPer1M: 1.75,
      outputPer1M: 14,
      sourceUrl: 'https://portkey.ai/models/openai',
      verifiedAt: '2026-05-18',
    },
    'gpt-5.3-codex': {
      cacheReadPer1M: 0.175,
      inputPer1M: 1.75,
      outputPer1M: 14,
      sourceUrl: 'https://portkey.ai/models/openai',
      verifiedAt: '2026-07-25',
    },
    'gpt-5.4': {
      cacheReadPer1M: 0.25,
      inputPer1M: 2.5,
      outputPer1M: 15,
      sourceUrl: 'https://pricepertoken.com/pricing-page/provider/openai',
      verifiedAt: '2026-07-25',
    },
    'gpt-5.4-mini': {
      cacheReadPer1M: 0.075,
      inputPer1M: 0.75,
      outputPer1M: 4.5,
      sourceUrl: 'https://pricepertoken.com/pricing-page/provider/openai',
      verifiedAt: '2026-07-25',
    },
    'gpt-5.4-nano': {
      cacheReadPer1M: 0.02,
      inputPer1M: 0.2,
      outputPer1M: 1.25,
      sourceUrl: 'https://developers.openai.com/api/docs/pricing',
      verifiedAt: '2026-07-25',
    },
    'gpt-5.4-pro': {
      inputPer1M: 30,
      outputPer1M: 180,
      sourceUrl: 'https://developers.openai.com/api/docs/pricing',
      verifiedAt: '2026-07-25',
    },
    'gpt-5.5': {
      cacheReadPer1M: 0.5,
      inputPer1M: 5,
      outputPer1M: 30,
      sourceUrl: 'https://pricepertoken.com/pricing-page/provider/openai',
      verifiedAt: '2026-07-25',
    },
    'gpt-5.5-pro': {
      inputPer1M: 30,
      outputPer1M: 180,
      sourceUrl: 'https://pricepertoken.com/pricing-page/provider/openai',
      verifiedAt: '2026-07-25',
    },
    'gpt-5.6-luna': {
      cacheReadPer1M: 0.02,
      hasInvisibleReasoningTokens: true,
      inputPer1M: 0.2,
      notes: 'Budget tier of the GPT-5.6 family (alongside gpt-5.6-sol and gpt-5.6-terra).',
      outputPer1M: 1.2,
      sourceUrl: 'https://developers.openai.com/api/docs/pricing',
      verifiedAt: '2026-08-18',
    },
    'gpt-5.6-sol': {
      cacheReadPer1M: 0.5,
      hasInvisibleReasoningTokens: true,
      inputPer1M: 5,
      outputPer1M: 30,
      sourceUrl: 'https://developers.openai.com/api/docs/models/gpt-5.6-sol',
      verifiedAt: '2026-07-25',
    },
    'gpt-5.6-terra': {
      cacheReadPer1M: 0.2,
      hasInvisibleReasoningTokens: true,
      inputPer1M: 2,
      outputPer1M: 12,
      sourceUrl: 'https://developers.openai.com/api/docs/pricing',
      verifiedAt: '2026-08-18',
    },
    o1: {
      cacheReadPer1M: 7.5,
      hasInvisibleReasoningTokens: true,
      inputPer1M: 15,
      notes:
        'Scheduled shutdown 2026-10-23 (OpenAI deprecations page) — migrate consumers to gpt-5.6-sol/terra/luna before then.',
      outputPer1M: 60,
      sourceUrl: 'https://developers.openai.com/api/docs/pricing',
      verifiedAt: '2026-08-18',
    },
    'o1-mini': {
      cacheReadPer1M: 0.55,
      hasInvisibleReasoningTokens: true,
      inputPer1M: 0.55,
      outputPer1M: 2.2,
      sourceUrl: 'https://developers.openai.com/api/docs/pricing',
      verifiedAt: '2026-05-18',
    },
    o3: {
      cacheReadPer1M: 0.5,
      hasInvisibleReasoningTokens: true,
      inputPer1M: 2,
      notes:
        'Scheduled shutdown 2026-12-11 (OpenAI deprecations page) — migrate consumers to gpt-5.6-sol/terra/luna before then.',
      outputPer1M: 8,
      sourceUrl: 'https://pricepertoken.com/pricing-page/provider/openai',
      verifiedAt: '2026-08-18',
    },
    'o3-mini': {
      cacheReadPer1M: 0.55,
      hasInvisibleReasoningTokens: true,
      inputPer1M: 1.1,
      notes:
        'Scheduled shutdown 2026-10-23 (OpenAI deprecations page) — migrate consumers to gpt-5.6-sol/terra/luna before then.',
      outputPer1M: 4.4,
      sourceUrl: 'https://developers.openai.com/api/docs/pricing',
      verifiedAt: '2026-08-18',
    },
    'o3-pro': {
      hasInvisibleReasoningTokens: true,
      inputPer1M: 20,
      outputPer1M: 80,
      sourceUrl: 'https://developers.openai.com/api/docs/pricing',
      verifiedAt: '2026-05-18',
    },
    'o4-mini': {
      cacheReadPer1M: 0.275,
      hasInvisibleReasoningTokens: true,
      inputPer1M: 1.1,
      notes:
        'Scheduled shutdown 2026-10-23 (OpenAI deprecations page) — migrate consumers to gpt-5.6-sol/terra/luna before then.',
      outputPer1M: 4.4,
      sourceUrl: 'https://pricepertoken.com/pricing-page/provider/openai',
      verifiedAt: '2026-08-18',
    },
  },

  gemini: {
    'gemini-2.5-flash': {
      cacheReadPer1M: 0.03,
      inputPer1M: 0.3,
      outputPer1M: 2.5,
      sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
      verifiedAt: '2026-07-25',
    },
    'gemini-2.5-flash-lite': {
      cacheReadPer1M: 0.01,
      inputPer1M: 0.1,
      outputPer1M: 0.4,
      sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
      verifiedAt: '2026-07-25',
    },
    'gemini-2.5-pro': {
      cacheReadPer1M: 0.125,
      inputPer1M: 1.25,
      longContextCacheReadPer1M: 0.25,
      longContextInputPer1M: 2.5,
      longContextOutputPer1M: 15,
      longContextThreshold: 200000,
      outputPer1M: 10,
      sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
      verifiedAt: '2026-07-25',
    },
    'gemini-3-flash-preview': {
      cacheReadPer1M: 0.05,
      inputPer1M: 0.5,
      outputPer1M: 3,
      sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
      verifiedAt: '2026-07-25',
    },
    'gemini-3.1-flash-lite': {
      cacheReadPer1M: 0.025,
      inputPer1M: 0.25,
      outputPer1M: 1.5,
      sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
      verifiedAt: '2026-07-25',
    },
    'gemini-3.1-pro': {
      cacheReadPer1M: 0.2,
      inputPer1M: 2,
      longContextCacheReadPer1M: 0.4,
      longContextInputPer1M: 4,
      longContextOutputPer1M: 18,
      longContextThreshold: 200000,
      outputPer1M: 12,
      sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
      verifiedAt: '2026-07-25',
    },
    'gemini-3.1-pro-preview': {
      cacheReadPer1M: 0.2,
      inputPer1M: 2,
      longContextCacheReadPer1M: 0.4,
      longContextInputPer1M: 4,
      longContextOutputPer1M: 18,
      longContextThreshold: 200000,
      outputPer1M: 12,
      sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
      verifiedAt: '2026-07-25',
    },
    'gemini-3.5-flash': {
      cacheReadPer1M: 0.15,
      inputPer1M: 1.5,
      outputPer1M: 9,
      sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
      verifiedAt: '2026-07-25',
    },
    'gemini-3.5-flash-lite': {
      cacheReadPer1M: 0.03,
      inputPer1M: 0.3,
      outputPer1M: 2.5,
      sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
      verifiedAt: '2026-07-25',
    },
    'gemini-3.6-flash': {
      cacheReadPer1M: 0.075,
      inputPer1M: 0.75,
      outputPer1M: 3.75,
      sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
      verifiedAt: '2026-08-18',
    },
    'gemini-3.7-flash': {
      cacheReadPer1M: 0.075,
      inputPer1M: 0.75,
      outputPer1M: 3.75,
      sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
      verifiedAt: '2026-08-18',
    },
  },

  deepseek: {
    'deepseek-chat': {
      cacheReadPer1M: 0.0028,
      deprecatedAliasFor: 'deepseek-v4-flash',
      inputPer1M: 0.14,
      notes:
        'Fully retired 2026-07-24 — this ID no longer routes anywhere, API calls error. Not a live alias despite deprecatedAliasFor; migrate any remaining callers to deepseek-v4-flash directly.',
      outputPer1M: 0.28,
      sourceUrl: 'https://api-docs.deepseek.com/quick_start/pricing',
      verifiedAt: '2026-08-18',
    },
    'deepseek-reasoner': {
      cacheReadPer1M: 0.0028,
      deprecatedAliasFor: 'deepseek-v4-flash',
      inputPer1M: 0.14,
      notes:
        'Fully retired 2026-07-24 — this ID no longer routes anywhere, API calls error. Not a live alias despite deprecatedAliasFor; migrate any remaining callers to deepseek-v4-flash directly.',
      outputPer1M: 0.28,
      sourceUrl: 'https://api-docs.deepseek.com/quick_start/pricing',
      verifiedAt: '2026-08-18',
    },
    'deepseek-v4-flash': {
      cacheReadPer1M: 0.007,
      inputPer1M: 0.22,
      notes:
        'Off-peak baseline rate. DeepSeek applies a ~2x peak surcharge 01:00–04:00 and 06:00–10:00 UTC — actual cost may be higher during those windows. computeCost() does not currently model time-of-day pricing.',
      outputPer1M: 0.66,
      sourceUrl: 'https://api-docs.deepseek.com/quick_start/pricing',
      verifiedAt: '2026-08-18',
    },
    'deepseek-v4-pro': {
      cacheReadPer1M: 0.022,
      inputPer1M: 0.66,
      notes:
        'Off-peak baseline rate. DeepSeek applies a ~2x peak surcharge 01:00–04:00 and 06:00–10:00 UTC — actual cost may be higher during those windows. computeCost() does not currently model time-of-day pricing.',
      outputPer1M: 1.98,
      sourceUrl: 'https://api-docs.deepseek.com/quick_start/pricing',
      verifiedAt: '2026-08-18',
    },
  },

  perplexity: {
    sonar: {
      inputPer1M: 1,
      outputPer1M: 1,
      sourceUrl: 'https://docs.perplexity.ai/guides/pricing',
      verifiedAt: '2026-07-25',
    },
    'sonar-deep-research': {
      inputPer1M: 2,
      outputPer1M: 8,
      partialCostCoverage: true,
      sourceUrl: 'https://docs.perplexity.ai/guides/pricing',
      verifiedAt: '2026-07-25',
    },
    'sonar-pro': {
      inputPer1M: 3,
      outputPer1M: 15,
      sourceUrl: 'https://docs.perplexity.ai/guides/pricing',
      verifiedAt: '2026-07-25',
    },
    'sonar-reasoning-pro': {
      inputPer1M: 2,
      outputPer1M: 8,
      sourceUrl: 'https://docs.perplexity.ai/guides/pricing',
      verifiedAt: '2026-07-25',
    },
  },

  xai: {
    'grok-4.5': {
      cacheReadPer1M: 0.3,
      inputPer1M: 2,
      longContextCacheReadPer1M: 0.6,
      longContextInputPer1M: 4,
      longContextOutputPer1M: 12,
      longContextThreshold: 200000,
      outputPer1M: 6,
      sourceUrl: 'https://docs.x.ai/developers/models/grok-4.5',
      verifiedAt: '2026-07-25',
    },
    'grok-4.6': {
      cacheReadPer1M: 0.5,
      inputPer1M: 2,
      longContextCacheReadPer1M: 1,
      longContextInputPer1M: 4,
      longContextOutputPer1M: 12,
      longContextThreshold: 200000,
      outputPer1M: 6,
      sourceUrl: 'https://docs.x.ai/developers/models/grok-4.6',
      verifiedAt: '2026-08-18',
    },
  },
};
